# This workflow will deploy the Serializers and the Validator to the sonatype
# staging environment. This will NOT automatically publish the artifacts. An
# authorized user must still manually close the staging repository first.

name: Generate and Deploy to Sonatype

on:
  push:
    branches: [ main ]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          server-id: ossrh
          server-username: sebbader
          server-password: ${{ secrets.SEBBADER_OSSHR_PASSWORD }}
          gpg-private-key: ${{ secrets.MYGPGKEY_SEC }}
          gpg-passphrase: ${{ secrets.GPG_KEY_PASSWORD }}

      - name: Build with Maven
        run: mvn -P MavenCentral -U clean license:format package

      - name: Publish to Apache Maven Central
        run: mvn -P MavenCentral -pl dataformat-json,dataformat-core license:format deploy -Dgpg.passphrase=${{ secrets.GPG_KEY_PASSWORD }}
        env:
          OSSRH_USERNAME: sebbader
          OSSRH_PASSWORD: ${{ secrets.SEBBADER_OSSHR_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_KEY_PASSWORD }}
